// Generated by CoffeeScript 2.3.0
var room;

room = {
  analyseRoom: function(room) {
    var h, i, j, len, source, sources, terrains, terrainsy, terrainxy, x, y;
    // if !Memory.sources
    Memory.sources = [];
    Memory.harvestingLocations = [];
    sources = room.find(FIND_SOURCES);
    h = 0;
    for (i = j = 0, len = sources.length; j < len; i = ++j) {
      source = sources[i];
      Memory.sources.push({
        'k': i,
        'id': source.id
      });
      terrains = room.lookForAtArea(LOOK_TERRAIN, source.pos.y - 1, source.pos.x - 1, source.pos.y + 1, source.pos.x + 1);
      for (y in terrains) {
        terrainsy = terrains[y];
        for (x in terrainsy) {
          terrainxy = terrainsy[x];
          if (terrainxy != "wall") {
            Memory.harvestingLocations.push({
              'source': i,
              'k': h++,
              'x': x,
              'y': y,
              'hasContainer': false,
              'hasHarvester': false
            });
          }
        }
      }
    }
  },
  initRoom: function(room) {
    var hL, i, pos, ref;
    ref = Memory.harvestingLocations;
    for (i in ref) {
      hL = ref[i];
      if (i < 5) {
        pos = new RoomPosition(hL.x, hL.y, room.name);
        if (pos.createConstructionSite(STRUCTURE_CONTAINER) === OK) {
          hL.hasContainer = true;
        }
      }
    }
  },
  run: function(room) {
    this.analyseRoom(room);
    this.initRoom(room);
  }
};

module.exports = room;

